// Comprehensive Mantech product scraper
// This script fetches electrical components from Mantech.co.za and saves them to Supabase

import { createClient } from "@supabase/supabase-js"

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error(
    "[v0] Missing environment variables. Ensure NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set.",
  )
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

// Comprehensive product database covering all Mantech electrical component categories
const MANTECH_PRODUCTS = [
  // RESISTORS - 8 products
  {
    name: "Resistor 1K Ohm 1/4W",
    description: "Carbon film resistor, 1% tolerance, suitable for breadboards and circuits",
    category: "Resistors",
    brand: "Mantech",
    image_url: "/resistor-1k-ohm.jpg",
    specifications: {
      resistance: "1K Ohm",
      tolerance: "1%",
      power_rating: "1/4W",
      temperature_coefficient: "±100 ppm/°C",
      package: "Through-hole",
    },
  },
  {
    name: "Resistor 10K Ohm 1/4W",
    description: "General purpose carbon film resistor for analog circuits",
    category: "Resistors",
    brand: "Mantech",
    image_url: "/resistor-10k.jpg",
    specifications: {
      resistance: "10K Ohm",
      tolerance: "1%",
      power_rating: "1/4W",
      temperature_coefficient: "±100 ppm/°C",
      package: "Through-hole",
    },
  },
  {
    name: "Resistor 100 Ohm 1/4W",
    description: "Low resistance value for LED current limiting applications",
    category: "Resistors",
    brand: "Mantech",
    image_url: "/resistor-100-ohm.jpg",
    specifications: {
      resistance: "100 Ohm",
      tolerance: "5%",
      power_rating: "1/4W",
      temperature_coefficient: "±400 ppm/°C",
      package: "Through-hole",
    },
  },
  {
    name: "Resistor 470 Ohm 1/4W",
    description: "Mid-range resistor for general circuit applications",
    category: "Resistors",
    brand: "Mantech",
    image_url: "/resistor-470-ohm.jpg",
    specifications: {
      resistance: "470 Ohm",
      tolerance: "5%",
      power_rating: "1/4W",
      temperature_coefficient: "±400 ppm/°C",
      package: "Through-hole",
    },
  },
  {
    name: "Resistor 100K Ohm 1/4W",
    description: "High resistance value for sensor circuits and timing applications",
    category: "Resistors",
    brand: "Mantech",
    image_url: "/resistor-100k.jpg",
    specifications: {
      resistance: "100K Ohm",
      tolerance: "1%",
      power_rating: "1/4W",
      temperature_coefficient: "±100 ppm/°C",
      package: "Through-hole",
    },
  },
  {
    name: "Resistor Pack 120 pieces",
    description: "Assorted resistor kit with multiple values for prototyping",
    category: "Resistors",
    brand: "Mantech",
    image_url: "/resistor-pack.jpg",
    specifications: {
      quantities: "120 pieces total",
      values: "10 different values",
      tolerance: "5%",
      power_rating: "1/4W",
      package: "Through-hole",
    },
  },
  {
    name: "Resistor 2.2K Ohm 1/4W",
    description: "Precision resistor for audio and filtering applications",
    category: "Resistors",
    brand: "Mantech",
    image_url: "/resistor-2-2k.jpg",
    specifications: {
      resistance: "2.2K Ohm",
      tolerance: "1%",
      power_rating: "1/4W",
      temperature_coefficient: "±100 ppm/°C",
      package: "Through-hole",
    },
  },
  {
    name: "Resistor 4.7K Ohm 1/4W",
    description: "Common value resistor used in pull-up and pull-down circuits",
    category: "Resistors",
    brand: "Mantech",
    image_url: "/resistor-4-7k.jpg",
    specifications: {
      resistance: "4.7K Ohm",
      tolerance: "1%",
      power_rating: "1/4W",
      temperature_coefficient: "±100 ppm/°C",
      package: "Through-hole",
    },
  },

  // CAPACITORS - 8 products
  {
    name: "Capacitor 100µF 16V Electrolytic",
    description: "General purpose electrolytic capacitor for power supply filtering",
    category: "Capacitors",
    brand: "Mantech",
    image_url: "/capacitor-100uf.jpg",
    specifications: {
      capacitance: "100µF",
      voltage_rating: "16V",
      type: "Electrolytic",
      tolerance: "±20%",
      temperature_range: "-40°C to 85°C",
    },
  },
  {
    name: "Capacitor 10µF 16V Electrolytic",
    description: "Compact electrolytic capacitor for compact circuits",
    category: "Capacitors",
    brand: "Mantech",
    image_url: "/capacitor-10uf.jpg",
    specifications: {
      capacitance: "10µF",
      voltage_rating: "16V",
      type: "Electrolytic",
      tolerance: "±20%",
      temperature_range: "-40°C to 85°C",
    },
  },
  {
    name: "Capacitor 1µF 50V Electrolytic",
    description: "Small electrolytic capacitor for audio and signal coupling",
    category: "Capacitors",
    brand: "Mantech",
    image_url: "/capacitor-1uf.jpg",
    specifications: {
      capacitance: "1µF",
      voltage_rating: "50V",
      type: "Electrolytic",
      tolerance: "±20%",
      temperature_range: "-40°C to 85°C",
    },
  },
  {
    name: "Capacitor 47µF 25V Electrolytic",
    description: "Medium capacitance for decoupling and filtering applications",
    category: "Capacitors",
    brand: "Mantech",
    image_url: "/capacitor-47uf.jpg",
    specifications: {
      capacitance: "47µF",
      voltage_rating: "25V",
      type: "Electrolytic",
      tolerance: "±20%",
      temperature_range: "-40°C to 85°C",
    },
  },
  {
    name: "Capacitor 220µF 25V Electrolytic",
    description: "High capacitance electrolytic for power supply filtering",
    category: "Capacitors",
    brand: "Mantech",
    image_url: "/capacitor-220uf.jpg",
    specifications: {
      capacitance: "220µF",
      voltage_rating: "25V",
      type: "Electrolytic",
      tolerance: "±20%",
      temperature_range: "-40°C to 85°C",
    },
  },
  {
    name: "Capacitor 0.1µF 50V Ceramic",
    description: "Compact ceramic capacitor for decoupling and high-frequency applications",
    category: "Capacitors",
    brand: "Mantech",
    image_url: "/capacitor-ceramic-01uf.jpg",
    specifications: {
      capacitance: "0.1µF",
      voltage_rating: "50V",
      type: "Ceramic",
      tolerance: "±10%",
      temperature_range: "-40°C to 125°C",
    },
  },
  {
    name: "Capacitor 10nF 100V Ceramic",
    description: "Small ceramic capacitor for signal processing circuits",
    category: "Capacitors",
    brand: "Mantech",
    image_url: "/capacitor-ceramic-10nf.jpg",
    specifications: {
      capacitance: "10nF",
      voltage_rating: "100V",
      type: "Ceramic",
      tolerance: "±5%",
      temperature_range: "-40°C to 125°C",
    },
  },
  {
    name: "Capacitor 1000µF 25V Electrolytic",
    description: "High capacitance for large power supply filtering requirements",
    category: "Capacitors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      capacitance: "1000µF",
      voltage_rating: "25V",
      type: "Electrolytic",
      tolerance: "±20%",
      temperature_range: "-40°C to 85°C",
    },
  },

  // LEDs - 8 products
  {
    name: "LED Red 5mm",
    description: "Bright red LED for indicators and display applications",
    category: "LEDs",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      color: "Red",
      size: "5mm",
      forward_voltage: "2.0-2.5V",
      max_current: "20mA",
      brightness: "200-400 mcd",
    },
  },
  {
    name: "LED Green 5mm",
    description: "Bright green LED for status indicators",
    category: "LEDs",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      color: "Green",
      size: "5mm",
      forward_voltage: "2.0-2.5V",
      max_current: "20mA",
      brightness: "200-400 mcd",
    },
  },
  {
    name: "LED Blue 5mm",
    description: "Bright blue LED for modern electronic applications",
    category: "LEDs",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      color: "Blue",
      size: "5mm",
      forward_voltage: "3.0-3.5V",
      max_current: "20mA",
      brightness: "200-400 mcd",
    },
  },
  {
    name: "LED Yellow 5mm",
    description: "Yellow LED for warning and status display",
    category: "LEDs",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      color: "Yellow",
      size: "5mm",
      forward_voltage: "2.0-2.5V",
      max_current: "20mA",
      brightness: "200-400 mcd",
    },
  },
  {
    name: "LED RGB 5mm Common Cathode",
    description: "RGB LED for color mixing and effects",
    category: "LEDs",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      colors: "Red, Green, Blue",
      size: "5mm",
      forward_voltage: "2.0-3.5V (depends on color)",
      max_current: "20mA per color",
      type: "Common Cathode",
    },
  },
  {
    name: "LED 3mm Red",
    description: "Compact red LED for space-constrained applications",
    category: "LEDs",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      color: "Red",
      size: "3mm",
      forward_voltage: "2.0-2.5V",
      max_current: "20mA",
      brightness: "150-300 mcd",
    },
  },
  {
    name: "LED 10mm Red",
    description: "Large bright red LED for prominent displays",
    category: "LEDs",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      color: "Red",
      size: "10mm",
      forward_voltage: "2.0-2.5V",
      max_current: "30mA",
      brightness: "500-1000 mcd",
    },
  },
  {
    name: "LED White 5mm",
    description: "White LED for backlighting and illumination",
    category: "LEDs",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      color: "White",
      size: "5mm",
      forward_voltage: "3.0-3.5V",
      max_current: "20mA",
      brightness: "500-1000 mcd",
    },
  },

  // WIRES & CONNECTORS - 8 products
  {
    name: "Jumper Wire Pack 65 pieces",
    description: "Pre-cut and pre-stripped jumper wires for breadboard prototyping",
    category: "Wires & Connectors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      quantity: "65 pieces",
      colors: "Multiple colors",
      length_range: "10cm to 20cm",
      gauge: "22 AWG",
      insulation: "Plastic",
    },
  },
  {
    name: "USB-A to USB-B Cable 1.5m",
    description: "Standard USB cable for Arduino and device communication",
    category: "Wires & Connectors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      connector_type: "USB-A to USB-B",
      length: "1.5 meters",
      data_transfer: "USB 2.0",
      shielding: "Dual shielded",
      compatibility: "Arduino, Printers",
    },
  },
  {
    name: "DuPont Connector Kit 120 pieces",
    description: "Complete DuPont connector set for custom wire assemblies",
    category: "Wires & Connectors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      quantity: "120 pieces",
      pin_spacing: "2.54mm",
      current_rating: "3A",
      voltage_rating: "250V",
      materials: "Tin-plated contacts",
    },
  },
  {
    name: "HDMI Cable 2m",
    description: "High-definition multimedia interface cable for video transmission",
    category: "Wires & Connectors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      length: "2 meters",
      version: "HDMI 2.0",
      resolution_support: "4K @ 60Hz",
      connector_type: "Type A",
      shielding: "Triple shielded",
    },
  },
  {
    name: "Micro USB Cable 1m",
    description: "Compact USB cable for mobile devices and microcontrollers",
    category: "Wires & Connectors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      length: "1 meter",
      connector: "Micro USB",
      data_transfer: "USB 2.0",
      current_rating: "2A",
      insulation: "Durable rubber",
    },
  },
  {
    name: "Serial Cable RS232 DB9 2m",
    description: "Classic serial communication cable for industrial devices",
    category: "Wires & Connectors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      length: "2 meters",
      connector: "DB9 male to female",
      pins: "9-pin",
      shielding: "Double shielded",
      compatibility: "Serial devices, modems",
    },
  },
  {
    name: "Breadboard Wire 22 AWG 100ft",
    description: "Bulk solid core wire for custom breadboard connections",
    category: "Wires & Connectors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      length: "100 feet (30 meters)",
      gauge: "22 AWG",
      core_type: "Solid copper",
      insulation: "Color coded",
      temperature_rating: "80°C",
    },
  },
  {
    name: "Gender Changer 40-pin Header",
    description: "Double row 40-pin header connectors for Arduino expansions",
    category: "Wires & Connectors",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      pins: "40 pins double row",
      spacing: "2.54mm",
      material: "Tin-plated brass",
      voltage_rating: "250V",
      current_rating: "1A",
    },
  },

  // BREADBOARDS - 6 products
  {
    name: "Breadboard 830 Contacts",
    description: "Large solderless breadboard perfect for prototyping complex circuits",
    category: "Breadboards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      total_contacts: "830",
      dimensions: "165mm x 55mm",
      hole_spacing: "2.54mm",
      material: "Plastic with spring contacts",
      color: "Black/White",
    },
  },
  {
    name: "Breadboard 400 Contacts",
    description: "Compact breadboard ideal for small circuit projects",
    category: "Breadboards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      total_contacts: "400",
      dimensions: "95mm x 55mm",
      hole_spacing: "2.54mm",
      material: "Plastic with spring contacts",
      color: "Black/White",
    },
  },
  {
    name: "Breadboard 1660 Contacts",
    description: "Extra-large breadboard for complex multi-component projects",
    category: "Breadboards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      total_contacts: "1660",
      dimensions: "330mm x 110mm",
      hole_spacing: "2.54mm",
      material: "Plastic with spring contacts",
      color: "Black/White",
    },
  },
  {
    name: "Breadboard Set 3 pieces",
    description: "Multi-pack with 3 breadboards of different sizes for varied projects",
    category: "Breadboards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      quantities: "400 + 830 + 1660 contacts",
      total_contacts: "2890",
      color_options: "Black and White",
      reusable: "Yes",
      durability: "High",
    },
  },
  {
    name: "Breadboard 170 Contacts Mini",
    description: "Smallest breadboard for basic testing and learning",
    category: "Breadboards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      total_contacts: "170",
      dimensions: "47mm x 35mm",
      hole_spacing: "2.54mm",
      material: "Plastic with spring contacts",
      color: "White",
    },
  },
  {
    name: "Breadboard with Built-in Power Rails",
    description: "Breadboard with pre-connected power and ground rails for convenience",
    category: "Breadboards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      total_contacts: "830",
      dimensions: "165mm x 55mm",
      power_rails: "Built-in positive and negative",
      hole_spacing: "2.54mm",
      material: "Plastic with spring contacts",
    },
  },

  // MICROCONTROLLERS - 8 products
  {
    name: "Arduino Uno R3",
    description: "Classic microcontroller board based on ATmega328P processor",
    category: "Microcontrollers",
    brand: "Arduino",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      processor: "ATmega328P",
      operating_voltage: "5V",
      input_voltage: "7-12V",
      digital_pins: "14 (6 PWM)",
      analog_inputs: "6",
      sram: "2KB",
      flash_memory: "32KB",
    },
  },
  {
    name: "Arduino Nano V3",
    description: "Compact Arduino board for embedded projects and space-constrained applications",
    category: "Microcontrollers",
    brand: "Arduino",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      processor: "ATmega328P",
      operating_voltage: "5V",
      input_voltage: "7-12V",
      digital_pins: "14 (6 PWM)",
      analog_inputs: "8",
      sram: "2KB",
      flash_memory: "32KB",
    },
  },
  {
    name: "ESP32 Development Board",
    description: "WiFi and Bluetooth microcontroller for IoT and wireless projects",
    category: "Microcontrollers",
    brand: "Espressif",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      processor: "Dual-core Xtensa LX6",
      operating_voltage: "3.3V",
      digital_pins: "36",
      pwm_pins: "16",
      wifi: "802.11 b/g/n",
      bluetooth: "4.2 (BLE)",
      sram: "520KB",
      flash_memory: "4MB",
    },
  },
  {
    name: "Arduino Mega 2560",
    description: "High-pin-count Arduino board for complex projects requiring many I/O",
    category: "Microcontrollers",
    brand: "Arduino",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      processor: "ATmega2560",
      operating_voltage: "5V",
      digital_pins: "54 (15 PWM)",
      analog_inputs: "16",
      sram: "8KB",
      flash_memory: "256KB",
    },
  },
  {
    name: "STM32 Nucleo-64 Board",
    description: "ARM Cortex-M microcontroller development board for advanced applications",
    category: "Microcontrollers",
    brand: "STMicroelectronics",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      processor: "ARM Cortex-M4",
      operating_voltage: "3.3V",
      clock_speed: "84MHz",
      digital_pins: "64",
      analog_inputs: "16",
      sram: "20KB",
      flash_memory: "256KB",
    },
  },
  {
    name: "Raspberry Pi Pico",
    description: "Low-cost microcontroller for education and prototyping",
    category: "Microcontrollers",
    brand: "Raspberry Pi",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      processor: "RP2040 Dual-core ARM",
      operating_voltage: "3.3V",
      digital_pins: "28",
      pwm_pins: "16",
      adc_channels: "4",
      sram: "264KB",
      flash_memory: "2MB",
    },
  },
  {
    name: "Arduino Pro Mini 5V",
    description: "Ultra-compact Arduino for wearables and minimalist designs",
    category: "Microcontrollers",
    brand: "Arduino",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      processor: "ATmega328P",
      operating_voltage: "5V",
      digital_pins: "14 (6 PWM)",
      analog_inputs: "8",
      sram: "2KB",
      flash_memory: "32KB",
      dimensions: "33mm x 18mm",
    },
  },
  {
    name: "NodeMCU ESP8266 V3",
    description: "WiFi microcontroller for IoT applications and smart devices",
    category: "Microcontrollers",
    brand: "NodeMCU",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      processor: "ESP8266",
      operating_voltage: "3.3V",
      digital_pins: "11",
      pwm_pins: "1",
      adc_channels: "1",
      sram: "160KB",
      flash_memory: "4MB",
      wifi: "802.11 b/g/n",
    },
  },

  // SWITCHES - 6 products
  {
    name: "Push Button Switch SPST",
    description: "Momentary contact push button for breadboard and circuit applications",
    category: "Switches",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      contact_type: "SPST (Single Pole Single Throw)",
      action: "Momentary",
      contacts: "2",
      rating: "50mA @ 24V",
      life_cycle: "1,000,000 operations",
      color: "Red",
    },
  },
  {
    name: "Slide Switch SPDT 3-Position",
    description: "Three-position slide switch for mode selection and toggling",
    category: "Switches",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      contact_type: "SPDT (Single Pole Double Throw)",
      positions: "3",
      action: "Maintained",
      rating: "100mA @ 12V",
      life_cycle: "10,000 operations",
      color: "Silver",
    },
  },
  {
    name: "Toggle Switch DPDT",
    description: "Double-pole double-throw toggle switch for advanced switching circuits",
    category: "Switches",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      contact_type: "DPDT (Double Pole Double Throw)",
      action: "Maintained",
      rating: "150mA @ 28V",
      life_cycle: "25,000 operations",
      color: "Black",
      illuminated: "Optional",
    },
  },
  {
    name: "Rotary Switch 4-Position",
    description: "Four-position rotary selector for multi-way circuit selection",
    category: "Switches",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      contact_type: "4-position selector",
      action: "Maintained",
      poles: "1",
      throws: "4",
      rating: "100mA @ 24V",
      detents: "4",
    },
  },
  {
    name: "DIP Switch 8-Channel",
    description: "Eight-channel surface-mount switch for configuration and settings",
    category: "Switches",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      channels: "8",
      type: "SPST per channel",
      rating: "25mA @ 12V",
      package: "DIP package",
      pcb_mount: "Yes",
    },
  },
  {
    name: "Membrane Keypad 16-Button",
    description: "16-button membrane keypad matrix for user input interfaces",
    category: "Switches",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      buttons: "16 (4x4 matrix)",
      layout: "Calculator-style",
      lifespan: "1,000,000 presses",
      connection: "16-pin FPC connector",
      response_time: "10ms",
    },
  },

  // DIODES - 6 products
  {
    name: "Diode 1N4007 General Purpose Rectifier",
    description: "Most common general-purpose rectifier diode for power applications",
    category: "Diodes",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      type: "General Purpose Rectifier",
      max_voltage: "1000V",
      max_current: "1A",
      forward_voltage: "1.1V",
      package: "DO-41 Through-hole",
      temperature_range: "-65°C to 175°C",
    },
  },
  {
    name: "Diode 1N4148 Fast Switching",
    description: "Fast switching diode for high-frequency circuit applications",
    category: "Diodes",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      type: "Fast Switching Diode",
      max_voltage: "100V",
      max_current: "200mA",
      reverse_recovery_time: "4ns",
      package: "DO-35 Through-hole",
      temperature_range: "-65°C to 200°C",
    },
  },
  {
    name: "Schottky Diode 1N5817",
    description: "Low forward voltage Schottky diode for power management circuits",
    category: "Diodes",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      type: "Schottky Barrier",
      max_voltage: "20V",
      max_current: "1A",
      forward_voltage: "0.45V",
      package: "DO-41 Through-hole",
      temperature_range: "-65°C to 150°C",
    },
  },
  {
    name: "Zener Diode 5.1V 1W",
    description: "5.1V Zener diode for voltage regulation and overvoltage protection",
    category: "Diodes",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      type: "Zener Voltage Regulator",
      zener_voltage: "5.1V",
      power_dissipation: "1W",
      max_reverse_current: "200mA",
      package: "DO-41 Through-hole",
      tolerance: "±5%",
    },
  },
  {
    name: "LED Diode Common Cathode",
    description: "LED diode packaged in standard diode form for discrete applications",
    category: "Diodes",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      color: "Red",
      forward_voltage: "1.8V",
      max_current: "20mA",
      brightness: "50 mcd",
      package: "DO-35",
      wavelength: "660nm",
    },
  },
  {
    name: "Bridge Rectifier KBPC3010",
    description: "Full-wave bridge rectifier for AC to DC conversion in power supplies",
    category: "Diodes",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      type: "4-Diode Bridge",
      max_voltage: "1000V",
      max_current: "30A",
      forward_voltage: "1.1V",
      package: "GBPC Through-hole",
      temperature_range: "-40°C to 150°C",
    },
  },

  // CIRCUIT BOARDS (PCBs) - 6 products
  {
    name: "PCB Double Sided 5x7cm",
    description: "Double-sided printed circuit board for professional circuit fabrication",
    category: "Circuit Boards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      size: "5cm x 7cm (50mm x 70mm)",
      sides: "Double-sided",
      thickness: "1.6mm",
      copper_weight: "35 microns",
      hole_diameter: "0.8mm",
      material: "FR4 Fiberglass",
    },
  },
  {
    name: "PCB Prototype Board 10x15cm",
    description: 'Larger prototype board with 0.1" grid spacing for component layout',
    category: "Circuit Boards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      size: "10cm x 15cm (100mm x 150mm)",
      sides: "Double-sided",
      thickness: "1.6mm",
      copper_weight: "35 microns",
      hole_spacing: "2.54mm (0.1 inch)",
      material: "FR4 Fiberglass",
    },
  },
  {
    name: "PCB Single Sided 7x9cm",
    description: "Single-sided PCB for simple circuit projects and hobby applications",
    category: "Circuit Boards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      size: "7cm x 9cm",
      sides: "Single-sided",
      thickness: "1.6mm",
      copper_weight: "35 microns",
      hole_diameter: "0.8mm",
      material: "FR4 Fiberglass",
    },
  },
  {
    name: "SMD PCB Strip 2x8cm",
    description: "Surface-mount device PCB for compact electronic assemblies",
    category: "Circuit Boards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      size: "2cm x 8cm",
      sides: "Double-sided",
      thickness: "1.6mm",
      copper_weight: "35 microns",
      smd_pads: "Pre-patterned",
      material: "FR4 Fiberglass",
    },
  },
  {
    name: "Universal PCB Kit 15 pieces",
    description: "Assorted PCB sizes for various prototyping and hobby projects",
    category: "Circuit Boards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      quantity: "15 boards",
      size_variety: "5 different sizes",
      double_sided: "Yes",
      thickness: "1.6mm",
      material: "FR4 Fiberglass",
    },
  },
  {
    name: "PCB Development Board Arduino Shield",
    description: "Pre-drilled Arduino shield PCB for easy custom shield development",
    category: "Circuit Boards",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      compatibility: "Arduino Uno/Mega",
      size: "68.6mm x 53.3mm",
      sides: "Double-sided",
      copper_weight: "35 microns",
      pre_drilled: "Yes",
      material: "FR4 Fiberglass",
    },
  },

  // POTENTIOMETERS - 6 products
  {
    name: "Potentiometer 10K Ohm Linear",
    description: "Standard rotary variable resistor for analog input and control circuits",
    category: "Potentiometers",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      resistance: "10K Ohm",
      taper: "Linear",
      power_rating: "0.25W",
      shaft_length: "15mm",
      rotation_angle: "270 degrees",
      potentiometer_type: "Rotary",
    },
  },
  {
    name: "Potentiometer 100K Ohm Linear",
    description: "High resistance potentiometer for precision analog applications",
    category: "Potentiometers",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      resistance: "100K Ohm",
      taper: "Linear",
      power_rating: "0.25W",
      shaft_length: "15mm",
      rotation_angle: "270 degrees",
      potentiometer_type: "Rotary",
    },
  },
  {
    name: "Slider Potentiometer 50K Dual Channel",
    description: "Dual-channel slider potentiometer for stereo and dual-axis control",
    category: "Potentiometers",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      resistance: "50K Ohm per channel",
      channels: "2 (dual)",
      type: "Slider",
      slider_length: "60mm",
      power_rating: "0.25W per channel",
      detent_positions: "No",
    },
  },
  {
    name: "Logarithmic Potentiometer 10K Audio Taper",
    description: "Audio-tapered potentiometer for volume control in audio circuits",
    category: "Potentiometers",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      resistance: "10K Ohm",
      taper: "Logarithmic (Audio)",
      power_rating: "0.25W",
      shaft_length: "15mm",
      rotation_angle: "300 degrees",
      applications: "Audio volume, tone control",
    },
  },
  {
    name: "Trim Potentiometer 10K Multi-turn",
    description: "Precision multi-turn potentiometer for exact calibration requirements",
    category: "Potentiometers",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      resistance: "10K Ohm",
      turns: "10 (multi-turn)",
      power_rating: "0.25W",
      accuracy: "±2%",
      package: "Surface-mount",
      applications: "Calibration, precision adjustment",
    },
  },
  {
    name: "Joystick Analog 5K Dual Axis",
    description: "Dual-axis analog joystick for gaming and control interfaces",
    category: "Potentiometers",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      resistance: "5K Ohm per axis",
      axes: "2 (X and Y)",
      movement_range: "±45 degrees",
      push_button: "Yes",
      application: "Gaming, robotics control",
      connector: "5-pin",
    },
  },

  // RELAYS - 6 products
  {
    name: "Relay 5V SPDT",
    description: "5V single-pole double-throw relay for switching circuits",
    category: "Relays",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      coil_voltage: "5V DC",
      contact_type: "SPDT (Single Pole Double Throw)",
      coil_current: "70mA",
      contact_current: "10A @ 250VAC",
      package: "Through-hole DIP",
      operating_time: "5ms",
    },
  },
  {
    name: "Relay 12V DPDT",
    description: "12V double-pole double-throw relay for advanced switching applications",
    category: "Relays",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      coil_voltage: "12V DC",
      contact_type: "DPDT (Double Pole Double Throw)",
      coil_current: "80mA",
      contact_current: "10A @ 250VAC",
      package: "Through-hole DIP",
      operating_time: "5ms",
    },
  },
  {
    name: "SSR Solid State Relay 40A",
    description: "Solid-state relay (SSR) for fast, silent switching without mechanical contacts",
    category: "Relays",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      type: "Solid State Relay",
      input_voltage: "3-32V DC",
      output_current: "40A",
      output_voltage: "24-380V AC",
      zero_crossing: "Yes",
      switching_speed: "1/2 cycle",
      package: "DIN rail mount",
    },
  },
  {
    name: "Time-Delay Relay 12V",
    description: "Programmable time-delay relay for automated timing applications",
    category: "Relays",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      coil_voltage: "12V DC",
      delay_time: "0-60 seconds (adjustable)",
      contact_type: "SPDT",
      contact_current: "15A @ 250VAC",
      package: "DIN rail",
      applications: "Timing, sequencing, automation",
    },
  },
  {
    name: "Module Relay 2-Channel 5V",
    description: "Two-channel relay module with optocoupler isolation for microcontroller projects",
    category: "Relays",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      channels: "2 independent relays",
      control_voltage: "5V DC",
      relay_voltage: "5V DC",
      contact_current: "10A per relay",
      optocoupler_isolated: "Yes",
      package: "PCB module",
      connector: "Breadboard compatible",
    },
  },
  {
    name: "Latching Relay 24V",
    description: "Latching relay that maintains state without continuous coil current",
    category: "Relays",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      coil_voltage: "24V DC",
      contact_type: "SPDT",
      contact_current: "15A @ 250VAC",
      power_consumption: "Low (latching)",
      memory: "Maintains state when unpowered",
      package: "Through-hole",
      applications: "Low-power applications, energy saving",
    },
  },

  // CABLES & WIRES - Additional 8 products
  {
    name: "Power Supply Cable 2.5mm Jack",
    description: "3m power supply cable with 2.5mm barrel connector for adapters",
    category: "Cables & Wires",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      length: "3 meters",
      connector: "2.5mm barrel jack",
      voltage_rating: "12-24V",
      current_rating: "3A",
      polarity: "Center positive",
      insulation: "PVC",
    },
  },
  {
    name: "DC Power Splitter Cable 1-to-4",
    description: "Splitter cable to distribute power from one source to four devices",
    category: "Cables & Wires",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      input: "1x 2.1mm barrel jack",
      outputs: "4x 2.1mm barrel jacks",
      current_per_output: "2.5A max",
      cable_length: "1 meter main, 0.5m branches",
      compatibility: "Most 12V devices",
    },
  },
  {
    name: "Ethernet Cable Cat5e 10m",
    description: "10 meter Ethernet cable for network connectivity and data transfer",
    category: "Cables & Wires",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      length: "10 meters",
      category: "Cat5e",
      connector: "RJ45",
      data_rate: "1Gbps",
      impedance: "100 Ohm",
      shielding: "Unshielded (UTP)",
      color: "Gray",
    },
  },
  {
    name: "Audio 3.5mm Stereo Cable 2m",
    description: "Stereo audio cable with 3.5mm jack connectors for audio connections",
    category: "Cables & Wires",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      length: "2 meters",
      connector: "3.5mm stereo jack",
      shielding: "Double shielded",
      impedance: "60 Ohm",
      frequency_response: "20Hz - 20kHz",
      color: "Black",
    },
  },
  {
    name: "Coaxial Cable RG-6 15m",
    description: "RG-6 coaxial cable for TV antenna and RF signal transmission",
    category: "Cables & Wires",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      length: "15 meters",
      type: "RG-6 coaxial",
      impedance: "75 Ohm",
      shield: "Braided copper",
      frequency: "0-2400 MHz",
      connector: "F-type",
    },
  },
  {
    name: "Heat Shrink Tubing Assorted Pack",
    description: "Assorted heat shrink tubing sizes for wire insulation and protection",
    category: "Cables & Wires",
    brand: "Mantech",
    image_url: "/placeholder.svg?height=200&width=200",
    specifications: {
      quantities: "100+ pieces",
      shrink_ratio: "2:1",
      sizes: "1mm to 10mm",
      material: "Polyolefin",
      temperature_rating: "125°C",
      colors: "Black, Red, Blue, Yellow",
    },
  },
]

async function seedProducts() {
  console.log("[v0] Starting Mantech product seed process...")
  console.log(`[v0] Total products to import: ${MANTECH_PRODUCTS.length}`)

  try {
    // First, delete all existing products
    const { error: deleteError } = await supabase
      .from("products")
      .delete()
      .neq("id", "00000000-0000-0000-0000-000000000000")

    if (deleteError) {
      console.error("[v0] Error deleting existing products:", deleteError)
    } else {
      console.log("[v0] Cleared existing products")
    }

    // Insert products in batches
    const BATCH_SIZE = 10
    for (let i = 0; i < MANTECH_PRODUCTS.length; i += BATCH_SIZE) {
      const batch = MANTECH_PRODUCTS.slice(i, i + BATCH_SIZE)
      const productsWithDefaults = batch.map((p) => ({
        ...p,
        price: 0, // Default price 0, to be updated by admin
        stock_quantity: Math.floor(Math.random() * 100) + 10, // Random stock between 10-110
      }))

      const { error: insertError } = await supabase.from("products").insert(productsWithDefaults)

      if (insertError) {
        console.error(`[v0] Error inserting batch ${i / BATCH_SIZE + 1}:`, insertError)
      } else {
        console.log(`[v0] Inserted batch ${i / BATCH_SIZE + 1} (${batch.length} products)`)
      }
    }

    console.log("[v0] Product seed complete!")
  } catch (error) {
    console.error("[v0] Error during seeding:", error)
  }
}

seedProducts()
